name: Bump VERSION

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grant write access to the repository
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Read current version
        id: get_version
        run: |
          VER=$(cat VERSION)
          echo "current=$VER" >> $GITHUB_OUTPUT

      - name: Bump patch
        id: bump
        run: |
          OLD=${{ steps.get_version.outputs.current }}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$OLD"
          PATCH=$((PATCH + 1))
          NEW="$MAJOR.$MINOR.$PATCH"
          echo "$NEW" > VERSION
          echo "new=$NEW" >> $GITHUB_OUTPUT

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add VERSION
          git commit -m "Bump version to ${{ steps.bump.outputs.new }}"
          git push